### ISSUE TITLE
계좌 기능 구현

### ISSUE THREAD

**Issue by ioannes486** [nyeongha/bankAccount#2]
#### 1. 필드 구현
- [x] 계좌번호, 소유자명, 잔고, 거래내역 필드 구현

#### 2. 메서드 구현
- [x] 입금, 출금을 void메서드로 구현
- [x] 잔고확인 메서드를 getter형태로 구현
- [x] ArrayLIst로 거래내역 확인 메서드 구현

**Comment by ioannes486** [comment]
### Transaction클래스의 필드를 private필드로 바꿔야 할까요?
현재 우리 프로젝트의 필드는 다음과 같이 default필드로 지정되어 있습니다.
![image](https://github.com/nyeongha/bankAccount/assets/120620360/0c69239e-526f-4537-ae2c-359d36ff2294)

이걸 private필드로 바꾸고 싶은데 과제의 클래스다이어그램을 보면 Tracsaction에 getter와 setter가 없어요
![image](https://github.com/nyeongha/bankAccount/assets/120620360/5379d75a-82e9-44c2-9791-ace143988b73)

이럴 때는 어떻게 해야할까요?
1. Transaction클래스 필드를 private으로 바꾸고 getter와 setter를 추가하기
2. 접근지정자를 default로 놔두고 getter와 setter추가 X

**Comment by nyeongha** [comment]
private로 바꾸고 getter와 setter를 추가하는게 맞는데 제가 초기 세팅할떄 private를 빼먹은것같습니다!추가해주시면돼요!

**Comment by Yang-soeun** [comment]
생성자는 필요하면 생성해도 된다고 했으니 private으로 하고 생성자를 이용한다면 getter와 setter 없이 구현할 수 있을것 같습니당~
